export const SUPABASE_URL = 'https://wqnqhmozprrxrcssesoq.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxbnFobW96cHJyeHJjc3Nlc29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk2NTQyNzUsImV4cCI6MjEwNTIzMDI3NX0.fDZyZXt0z6NjkDRj9sM5jIdHnoZY5vOHkDQp4h95GMY';

export const translations = {
    it: {
        title: "SmartTable Manager",
        calendar: "Calendario",
        floorTitle: "Pianta Interattiva & Muri Dinamici",
        floorSubtitle: "Clicca sui tavoli per prenotare. In modifica puoi ridimensionarli, ruotarli, regolarne i posti e modellare i muri.",
        timeFilter: "Fascia:",
        legendTitle: "Legenda Tavoli:",
        free: "Libero",
        partial: "Parziale",
        full: "Completo",
        modalTitle: "Prenotazioni Tavolo",
        existingTitle: "Orari già riservati:",
        formTitle: "Nuova prenotazione",
        lblStart: "Dalle",
        lblEnd: "Fino alle",
        lblName: "Nome Cliente",
        lblGuests: "Persone",
        lblPhone: "Telefono",
        privacyText: "Il cliente ha già accettato l'Informativa sulla Privacy in precedenza.",
        privacyNewText: "Ho letto e accetto l'Informativa sulla Privacy e acconsento al trattamento dei miei dati. *",
        btnSave: "Salva Prenotazione",
        seats: "Posti",
        noBookings: "Nessuna prenotazione oggi.",
        editModeOn: "Salva & Chiudi Modifica",
        editModeOff: "Modifica Sala & Muri / Wände bearbeiten",
        newTable: "Nuovo Tavolo",
        newRoom: "+ Nuova Sala",
        addWall: "+ Aggiungi Muro",
        roomModalTitle: "Aggiungi Nuova Sala",
        lblRoomName: "Nome Sala",
        btnSaveRoom: "Crea Sala",
        rotateTable: "Ruota 90° 🔄",
        errCapacity: "Il numero di ospiti supera la capienza di questo tavolo (max posti: ",
        errOverlap: "Attenzione: questo tavolo è già occupato nell'orario selezionato!",
        dailySummaryTitle: "Riepilogo Prenotazioni del Giorno",
        dailySummarySub: "Elenco completo e totale ospiti attesi per la data selezionata.",
        totalGuestsLabel: "Totale Ospiti Attesi",
        thTime: "Orario",
        thTable: "Tavolo",
        thName: "Cliente",
        thGuests: "Persone",
        thPhone: "Telefono",
        thActions: "Azioni",
        noDailyBookings: "Nessuna prenotazione registrata per questa data.",
        timeFilterAll: "Tutta la giornata",
        timeFilterLunch: "Pranzo (12-15)",
        timeFilterDinner1: "Cena 1 (18-21)",
        timeFilterDinner2: "Cena 2 (21-23:30)"
    },
    de: {
        title: "SmartTable Manager",
        calendar: "Kalender",
        floorTitle: "Interaktiver Raum- & Wandplan",
        floorSubtitle: "Klicken zum Reservieren. Im Modus Grösse anpassen, drehen, Plätze ändern und Wände bearbeiten.",
        timeFilter: "Zeitfenster:",
        legendTitle: "Tisch-Legende:",
        free: "Frei",
        partial: "Teilweise",
        full: "Voll",
        modalTitle: "Tisch-Reservierungen",
        existingTitle: "Bereits reservierte Zeiten:",
        formTitle: "Neue Reservierung",
        lblStart: "Von",
        lblEnd: "Bis",
        lblName: "Kundenname",
        lblGuests: "Personen",
        lblPhone: "Telefon",
        privacyText: "Der Kunde hat die Datenschutzbestimmungen bereits akzeptiert.",
        privacyNewText: "Ich habe die Datenschutzbestimmungen gelesen und akzeptiere sie. *",
        btnSave: "Reservierung speichern",
        seats: "Plätze",
        noBookings: "Keine Reservierungen.",
        editModeOn: "Speichern & Fertig",
        editModeOff: "Raum & Wände bearbeiten",
        newTable: "Neuer Tisch",
        newRoom: "+ Neuer Saal",
        addWall: "+ Wand hinzufügen",
        roomModalTitle: "Neuen Saal hinzufügen",
        lblRoomName: "Saalname",
        btnSaveRoom: "Saal erstellen",
        rotateTable: "90° drehen 🔄",
        errCapacity: "Die Anzahl der Gäste überschreitet die Kapazität (max. Plätze: ",
        errOverlap: "Achtung: Dieser Tisch ist zur gewählten Zeit bereits belegt!",
        dailySummaryTitle: "Tages-Reservierungsübersicht",
        dailySummarySub: "Vollständige Liste und erwartete Gäste für das gewählte Datum.",
        totalGuestsLabel: "Erwartete Gäste",
        thTime: "Uhrzeit",
        thTable: "Tisch",
        thName: "Kunde",
        thGuests: "Personen",
        thPhone: "Telefon",
        thActions: "Aktion",
        noDailyBookings: "Keine Reservierungen für dieses Datum.",
        timeFilterAll: "Ganztägig",
        timeFilterLunch: "Mittagessen (12-15)",
        timeFilterDinner1: "Abendessen 1 (18-21)",
        timeFilterDinner2: "Abendessen 2 (21-23:30)"
    }
};

export let state = {
    supabaseClient: null,
    currentRestaurantId: null,
    currentRestaurantName: '',
    currentLang: 'it',
    currentDate: new Date(),
    tables: [],
    bookings: [],
    rooms: [
        { 
            id: 'sala-principale', 
            name: 'Sala Principale / Hauptsaal',
            walls: [
                { x1: 20, y1: 20, x2: 700, y2: 20, type: 'wall' },
                { x1: 700, y1: 20, x2: 700, y2: 500, type: 'wall' },
                { x1: 700, y1: 500, x2: 350, y2: 500, type: 'wall' },
                { x1: 350, y1: 500, x2: 350, y2: 350, type: 'door' },
                { x1: 350, y1: 350, x2: 20, y2: 350, type: 'wall' },
                { x1: 20, y1: 350, x2: 20, y2: 20, type: 'wall' }
            ]
        },
        { 
            id: 'veranda', 
            name: 'Veranda / Terrasse',
            walls: [
                { x1: 20, y1: 20, x2: 500, y2: 20, type: 'wall' },
                { x1: 500, y1: 20, x2: 500, y2: 400, type: 'wall' },
                { x1: 500, y1: 400, x2: 20, y2: 400, type: 'wall' },
                { x1: 20, y1: 400, x2: 20, y2: 20, type: 'wall' }
            ]
        }
    ],
    currentRoomId: 'sala-principale',
    isEditMode: false
};
